### ISSUE TITLE
插件免费，进了bob还是限制次数，本来是这样的还是我操作不对

### ISSUE THREAD

**Issue by botshen** [akl7777777/deepl-free-translate-service#1]

**Comment by akl7777777** [comment]
如果你是使用的bob插件,先更新到最新版

https://github.com/akl7777777/bob-plugin-akl-deepl-free-translate/releases/download/v0.1.2/bob-plugin-akl-deepl-translate_v0.1.2.bobplugin

然后,再试下能不能使用.如果插件返回结果429,就登录[deepl翻译网页版](https://www.deepl.com/translator)看下当前ip下是否访问过于频繁,如果网页版不能访问,就说明需要你当前的ip暂时被限制了(尤其是在公司的网络环境,同一个IP访问deepl的人大概不止你一个吧),不过不用担心,等待半个小时左右大概就可以了,或者你换一台其他IP地址的机器试试先

**Comment by akl7777777** [comment]
还有,补充一点,如果你失败了,不要一直尝试,多等一下,如果你一直尝试,他的等待时间可能会一直往后延

**Comment by botshen** [comment]
好的，感谢
